// src/components/LegalModals.jsx
import React from 'react';
import { X, ShieldCheck, Lock, EyeOff, FileText, Check } from 'lucide-react';

export function PrivacyPolicyModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-stone-900/40 backdrop-blur-md animate-fade-in">
      <div className="w-full max-w-2xl max-h-[85vh] flex flex-col rounded-3xl bg-white/95 border border-stone-200/80 shadow-2xl overflow-hidden font-sans">
        
        {/* Header */}
        <div className="px-6 py-5 border-b border-stone-100 flex items-center justify-between bg-stone-50/50">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-rose-100 text-rose-600 flex items-center justify-center border border-rose-200">
              <ShieldCheck size={18} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-stone-900 leading-tight">Privacy Policy & Data Sovereignty</h3>
              <p className="text-xs font-mono text-stone-400">LAST UPDATED // AUGUST 2026</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-stone-100 hover:bg-stone-200 text-stone-500 flex items-center justify-center transition-colors cursor-pointer"
          >
            <X size={15} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-5 text-sm text-stone-600 leading-relaxed scrollbar-thin">
          <div className="p-4 rounded-2xl bg-rose-50/60 border border-rose-100 flex items-start gap-3">
            <Lock size={20} className="text-rose-500 shrink-0 mt-0.5" />
            <div>
              <h4 className="font-bold text-stone-900 text-xs uppercase font-mono tracking-wider">Zero Commercial Data Sale Guarantee</h4>
              <p className="text-xs text-stone-600 mt-0.5">
                Serene Cycle will never sell, monetize, or share your biological cycle logs, symptom notes, or personal metrics with third-party advertisers, insurance providers, or data brokers.
              </p>
            </div>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1.5">1. Information We Collect</h4>
            <p>
              We collect only the minimal data required to calculate your biological phases: email address, optional full name, user-configured cycle length preferences, and cycle logs (period dates, symptoms, basal temperatures, flow intensities, and mood notes).
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1.5">2. Security & Encryption</h4>
            <p>
              Your data is secured using Supabase Row Level Security (RLS) policies. Only your authenticated user account can read or modify your personal logs. All database transmissions are encrypted via TLS 1.3.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1.5">3. Your Data Rights & Deletion</h4>
            <p>
              You maintain full sovereignty over your biological data. At any time, you can request full export of your logs or execute a permanent one-click account deletion directly from your Profile settings.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1.5">4. Medical Disclaimer</h4>
            <p className="text-xs text-stone-500 italic">
              Serene Cycle is an educational and self-tracking application. Predictions generated by the system are statistical estimates based on user logs and do not constitute medical diagnosis or birth control confirmation.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-stone-100 bg-stone-50/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl bg-stone-900 text-white font-mono text-xs font-bold hover:bg-stone-800 transition-all cursor-pointer"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
}

export function TermsOfServiceModal({ isOpen, onClose }) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-[150] flex items-center justify-center p-4 bg-stone-900/40 backdrop-blur-md animate-fade-in">
      <div className="w-full max-w-2xl max-h-[85vh] flex flex-col rounded-3xl bg-white/95 border border-stone-200/80 shadow-2xl overflow-hidden font-sans">
        
        {/* Header */}
        <div className="px-6 py-5 border-b border-stone-100 flex items-center justify-between bg-stone-50/50">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-purple-100 text-purple-600 flex items-center justify-center border border-purple-200">
              <FileText size={18} />
            </div>
            <div>
              <h3 className="text-lg font-bold text-stone-900 leading-tight">Terms of Service</h3>
              <p className="text-xs font-mono text-stone-400">LAST UPDATED // AUGUST 2026</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-full bg-stone-100 hover:bg-stone-200 text-stone-500 flex items-center justify-center transition-colors cursor-pointer"
          >
            <X size={15} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto space-y-4 text-sm text-stone-600 leading-relaxed scrollbar-thin">
          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1">1. Acceptance of Terms</h4>
            <p>
              By creating an account or using Serene Cycle, you agree to these Terms of Service. If you do not agree, please discontinue using the service.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1">2. User Account Integrity</h4>
            <p>
              You are responsible for maintaining the confidentiality of your login credentials and for all activities conducted under your user account.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1">3. Non-Diagnostic Use</h4>
            <p>
              Serene Cycle provides biometric estimations for wellness and self-awareness. It should not replace professional medical consultation, diagnostic tests, or clinical healthcare advice.
            </p>
          </div>

          <div>
            <h4 className="font-bold text-stone-900 text-base mb-1">4. Service Availability</h4>
            <p>
              We strive for high availability but do not guarantee uninterrupted access. We reserve the right to modify or enhance feature offerings to maintain quality.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-stone-100 bg-stone-50/50 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl bg-stone-900 text-white font-mono text-xs font-bold hover:bg-stone-800 transition-all cursor-pointer"
          >
            Close Terms
          </button>
        </div>
      </div>
    </div>
  );
}
